### ISSUE TITLE
Issue on reproduce the work.

### ISSUE THREAD

**Issue by orchestor** [Kyubyong/sudoku#1]
Just load the data and model. 

~~~
python test.py         
~~~
give me the following issue.  Sounds model can not find in checkpoint. any pointer to this issue?

~~~~~
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key lyr-conv_1/variance not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key lyr-conv_1/beta not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key lyr-conv_1/gamma not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key lyr-conv_9/variance not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key lyr-conv_1/mean not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key lyr-conv_10/beta not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key lyr-conv_10/W not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key lyr-conv_9/mean not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key lyr-conv_1/W not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key lyr-conv_10/gamma not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key lyr-conv_10/variance not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key lyr-conv_11/b not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key lyr-conv_9/gamma not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key lyr-conv_11/W not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key lyr-conv_2/beta not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key lyr-conv_10/mean not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key lyr-conv_2/mean not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key lyr-conv_2/W not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key lyr-conv_2/variance not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key lyr-conv_3/beta not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key lyr-conv_2/gamma not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key lyr-conv_9/beta not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key lyr-conv_3/gamma not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key lyr-conv_3/mean not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key lyr-conv_4/W not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key lyr-conv_4/beta not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key lyr-conv_9/W not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key lyr-conv_4/variance not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key lyr-conv_4/gamma not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key lyr-conv_5/W not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key lyr-conv_3/W not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key lyr-conv_4/mean not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key lyr-conv_5/beta not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key lyr-conv_3/variance not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key lyr-conv_8/variance not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key lyr-conv_5/mean not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key lyr-conv_5/gamma not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key lyr-conv_5/variance not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key lyr-conv_6/mean not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key lyr-conv_6/beta not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key lyr-conv_6/W not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key lyr-conv_8/mean not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key lyr-conv_6/gamma not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key lyr-conv_6/variance not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key lyr-conv_7/gamma not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key lyr-conv_7/W not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key lyr-conv_8/gamma not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key lyr-conv_7/beta not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key lyr-conv_8/W not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key lyr-conv_7/variance not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key lyr-conv_7/mean not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key lyr-conv_8/beta not found in checkpoint
Traceback (most recent call last):
  File "test.py", line 730, in <module>
    test1()
  File "test.py", line 650, in test1
    saver.restore(sess, tf.train.latest_checkpoint('asset/train/ckpt'))
  File "/Users/grant/project/sudoku/sudoku/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1388, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/Users/grant/project/sudoku/sudoku/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 766, in run
    run_metadata_ptr)
  File "/Users/grant/project/sudoku/sudoku/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 964, in _run
    feed_dict_string, options, run_metadata)
  File "/Users/grant/project/sudoku/sudoku/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1014, in _do_run
    target_list, options, run_metadata)
  File "/Users/grant/project/sudoku/sudoku/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1034, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key lyr-conv_1/variance not found in checkpoint
	 [[Node: save/RestoreV2_6 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_6/tensor_names, save/RestoreV2_6/shape_and_slices)]]

Caused by op u'save/RestoreV2_6', defined at:
  File "test.py", line 730, in <module>
    test1()
  File "test.py", line 649, in test1
    saver = tf.train.Saver()
  File "/Users/grant/project/sudoku/sudoku/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1000, in __init__
    self.build()
  File "/Users/grant/project/sudoku/sudoku/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1030, in build
    restore_sequentially=self._restore_sequentially)
  File "/Users/grant/project/sudoku/sudoku/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 624, in build
    restore_sequentially, reshape)
  File "/Users/grant/project/sudoku/sudoku/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 361, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/Users/grant/project/sudoku/sudoku/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 200, in restore_op
    [spec.tensor.dtype])[0])
  File "/Users/grant/project/sudoku/sudoku/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 441, in restore_v2
    dtypes=dtypes, name=name)
  File "/Users/grant/project/sudoku/sudoku/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 759, in apply_op
    op_def=op_def)
  File "/Users/grant/project/sudoku/sudoku/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2240, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/Users/grant/project/sudoku/sudoku/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1128, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): Key lyr-conv_1/variance not found in checkpoint
	 [[Node: save/RestoreV2_6 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_6/tensor_names, save/RestoreV2_6/shape_and_slices)]]

**Comment by Kyubyong** [comment]
Have you downloaded the pretrained model file?
